name: 'SwordLevel'
version: 3.0
description: 'Sistema de level para itens e players.'

author: 'Neitan96'
website: 'http://www.nathanalmeida.com.br/'

main: 'br.neitan96.swordlevelv3.SwordLevel'

commands:
  swordlevel:
    description: 'Ver todos os comandos do SwordLevel'
    aliases: ['sword', 'sl']
    permission: 'swordlevel.help'
    usage: '/<command>'
  swordlevel view:
    description: 'Ver o level e xp do equivalente ao item na mao.'
    permission: 'swordlevel.view'
    usage: '/<command>'
  swordlevel bonus:
    description: 'Ver os bonus e xp do equivalente ao item na mao.'
    permission: 'swordlevel.bonus'
    usage: '/<command>'
  # Comando mostra somente de grupos armazenados por player
  swordlevel viewall:
    description: 'Ver o level e xp de todos seus grupos.'
    permission: 'swordlevel.viewall'
    usage: '/<command>'
  swordlevel bonusall:
    description: 'Ver os bonus e xp de todos seus grupos.'
    permission: 'swordlevel.bonusall'
    usage: '/<command>'
  swordlevel setlevel:
    description: 'Define o level em um grupo para um player'
    permission: 'swordlevel.admin'
    usage: '/<command> <player> <grupo> <level>'
  swordlevel addlevel:
    description: 'Adiciona level em um grupo para um player'
    permission: 'swordlevel.admin'
    usage: '/<command> <player> <grupo> <level>'
  swordlevel setxp:
    description: 'Define o xp em um grupo para um player'
    permission: 'swordlevel.admin'
    usage: '/<command> <player> <grupo> <xp>'
  swordlevel addxp:
    description: 'Adiciona xp em um grupo para um player'
    permission: 'swordlevel.admin'
    usage: '/<command> <player> <grupo> <xp>'
  swordlevel viewplayer:
    description: 'Ver informacoes de um player, Grupo, Item na mao, Level, Xp, Bonus'
    permission: 'swordlevel.admin'
    usage: '/<command> <player> [grupo]'
